version: '3'
services:
  connector-zerofox:
    image: opencti/connector-zerofox:latest
    environment:
      - CONNECTOR_NAME=Zerofox
      - CONNECTOR_SCOPE=zerofox # MIME type or Stix Object
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=debug
      - CONNECTOR_RUN_EVERY=${CONNECTOR_RUN_EVERY}
      - ZEROFOX_USERNAME=ChangeMe
      - ZEROFOX_PASSWORD=ChangeMe
    depends_on:
      opencti-dev-platform:
        condition: service_started
    restart: always
